source "http://rubygems.org"

gem "cucumber"
gem "fig_newton"
gem "gmail"
gem "hub"
gem "nokogiri"
gem "page-object"
gem "parallel_tests"
gem "rake"
gem "require_all"
gem "rest-client"
gem "roo"
gem "rspec"
gem "rubocop"
gem "watir"
gem "eyes_selenium"
gem "webdrivers"
gem "selenium-webdriver"
gem "net-ssh"
gem "imatcher"
gem "capybara-screenshot"
gem "capybara-screenshot-diff"
gem "oily_png", platform: :ruby
gem "faker"
gem "mongo"